import { DiodeFilter } from '@mode-7/mod';
import { ModuleDefinition } from './types';

export const MODULE_DEFINITIONS: Record<string, ModuleDefinition> = {
  ToneGenerator: {
    type: 'ToneGenerator',
    label: 'Tone Generator',
    category: 'source',
    color: '#667eea',
    inputs: 0,
    outputs: 1,
    defaultParams: { frequency: 440, gain: 0.3, waveform: 'square' },
  },
  NoiseGenerator: {
    type: 'NoiseGenerator',
    label: 'Noise Generator',
    category: 'source',
    color: '#a18cd1',
    inputs: 0,
    outputs: 1,
    defaultParams: { gain: 0.3, type: 'white' },
  },
  Microphone: {
    type: 'Microphone',
    label: 'Microphone',
    category: 'source',
    color: '#f093fb',
    inputs: 0,
    outputs: 1,
    defaultParams: { gain: 1.0 },
  },
  MP3Deck: {
    type: 'MP3Deck',
    label: 'MP3 Deck',
    category: 'source',
    color: '#4facfe',
    inputs: 0,
    outputs: 1,
    defaultParams: { src: '', gain: 1.0, loop: false, isPlaying: false },
  },
  StreamingAudioDeck: {
    type: 'StreamingAudioDeck',
    label: 'Stream Deck',
    category: 'source',
    color: '#43e97b',
    inputs: 0,
    outputs: 1,
    defaultParams: { url: '', gain: 1.0, isPlaying: false },
  },
  LFO: {
    type: 'LFO',
    label: 'LFO',
    category: 'cv',
    color: '#ff9a9e',
    inputs: 0,
    outputs: 1,
    defaultParams: { frequency: 1, amplitude: 1, waveform: 'sine' },
  },
  ADSR: {
    type: 'ADSR',
    label: 'ADSR',
    category: 'cv',
    color: '#fad0c4',
    inputs: 0,
    outputs: 1,
    defaultParams: { attack: 0.01, decay: 0.1, sustain: 0.7, release: 0.3 },
  },
  Sequencer: {
    type: 'Sequencer',
    label: 'Sequencer',
    category: 'cv',
    color: '#ffecd2',
    inputs: 0,
    outputs: 2, // CV output + Gate output
    defaultParams: { steps: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5], bpm: 120, isPlaying: false },
  },
  Clock: {
    type: 'Clock',
    label: 'Clock',
    category: 'cv',
    color: '#fddb92',
    inputs: 0,
    outputs: 1,
    defaultParams: { bpm: 120, isRunning: false },
  },
  Delay: {
    type: 'Delay',
    label: 'Delay',
    category: 'processor',
    color: '#fa709a',
    inputs: 1,
    outputs: 1,
    defaultParams: { time: 0.5, feedback: 0.3, wet: 0.5 },
  },
  Reverb: {
    type: 'Reverb',
    label: 'Reverb',
    category: 'processor',
    color: '#fee140',
    inputs: 1,
    outputs: 1,
    defaultParams: { wet: 0.3, duration: 2.0, decay: 2.0 },
  },
  Filter: {
    type: 'Filter',
    label: 'Filter',
    category: 'processor',
    color: '#38f9d7',
    inputs: 1,
    outputs: 1,
    defaultParams: { frequency: 1000, Q: 1, type: 'lowpass', gain: 0 },
  },
  Compressor: {
    type: 'Compressor',
    label: 'Compressor',
    category: 'processor',
    color: '#f093fb',
    inputs: 1,
    outputs: 1,
    defaultParams: { threshold: -24, knee: 30, ratio: 12, attack: 0.003, release: 0.25 },
  },
  Distortion: {
    type: 'Distortion',
    label: 'Distortion',
    category: 'processor',
    color: '#ff6b9d',
    inputs: 1,
    outputs: 1,
    defaultParams: { amount: 50 },
  },
  DiodeFilter: {
    type: 'DiodeFilter',
    label: 'Diode Filter',
    category: 'processor',
    color: '#ff6b9d',
    inputs: 1,
    outputs: 1,
    defaultParams: { cutoff: 1.0, resounance: 1.0, drive: 0.5 },
  },
  Panner: {
    type: 'Panner',
    label: 'Panner',
    category: 'processor',
    color: '#c471f5',
    inputs: 1,
    outputs: 1,
    defaultParams: { pan: 0 },
  },
  EQ: {
    type: 'EQ',
    label: 'EQ',
    category: 'processor',
    color: '#fbc2eb',
    inputs: 1,
    outputs: 1,
    defaultParams: { lowGain: 0, midGain: 0, highGain: 0, lowFreq: 250, highFreq: 4000 },
  },
  Chorus: {
    type: 'Chorus',
    label: 'Chorus',
    category: 'processor',
    color: '#a6c1ee',
    inputs: 1,
    outputs: 1,
    defaultParams: { rate: 1.5, depth: 0.002, delay: 0.02, wet: 0.5 },
  },
  Phaser: {
    type: 'Phaser',
    label: 'Phaser',
    category: 'processor',
    color: '#f093fb',
    inputs: 1,
    outputs: 1,
    defaultParams: { rate: 0.5, depth: 500, feedback: 0.5, baseFreq: 800 },
  },
  Flanger: {
    type: 'Flanger',
    label: 'Flanger',
    category: 'processor',
    color: '#fbc2eb',
    inputs: 1,
    outputs: 1,
    defaultParams: { rate: 0.25, depth: 0.003, feedback: 0.5, delay: 0.005 },
  },
  Tremolo: {
    type: 'Tremolo',
    label: 'Tremolo',
    category: 'processor',
    color: '#a1c4fd',
    inputs: 1,
    outputs: 1,
    defaultParams: { rate: 5, depth: 0.5 },
  },
  BitCrusher: {
    type: 'BitCrusher',
    label: 'BitCrusher',
    category: 'processor',
    color: '#d4fc79',
    inputs: 1,
    outputs: 1,
    defaultParams: { bitDepth: 8, sampleReduction: 1 },
  },
  Limiter: {
    type: 'Limiter',
    label: 'Limiter',
    category: 'processor',
    color: '#96e6a1',
    inputs: 1,
    outputs: 1,
    defaultParams: { threshold: -1, release: 0.05 },
  },
  Gate: {
    type: 'Gate',
    label: 'Gate',
    category: 'processor',
    color: '#84fab0',
    inputs: 1,
    outputs: 1,
    defaultParams: { threshold: -40, attack: 0.01, release: 0.1 },
  },
  AutoWah: {
    type: 'AutoWah',
    label: 'AutoWah',
    category: 'processor',
    color: '#ffecd2',
    inputs: 1,
    outputs: 1,
    defaultParams: { sensitivity: 1000, baseFreq: 200, maxFreq: 2000, Q: 5 },
  },
  RingModulator: {
    type: 'RingModulator',
    label: 'RingMod',
    category: 'processor',
    color: '#ff9a9e',
    inputs: 1,
    outputs: 1,
    defaultParams: { frequency: 440, wet: 0.5 },
  },
  VCA: {
    type: 'VCA',
    label: 'VCA',
    category: 'processor',
    color: '#a8edea',
    inputs: 1,
    outputs: 1,
    defaultParams: { gain: 1.0, cvAmount: 1.0 },
  },
  CrossFade: {
    type: 'CrossFade',
    label: 'CrossFade',
    category: 'mixer',
    color: '#30cfd0',
    inputs: 2,
    outputs: 1,
    defaultParams: { mix: 0.5 },
  },
  Mixer: {
    type: 'Mixer',
    label: 'Mixer',
    category: 'mixer',
    color: '#a8edea',
    inputs: 4,
    outputs: 1,
    defaultParams: { levels: [1.0, 1.0, 1.0, 1.0] },
  },
  Monitor: {
    type: 'Monitor',
    label: 'Monitor',
    category: 'output',
    color: '#ff6b6b',
    inputs: 1,
    outputs: 0,
    defaultParams: { gain: 1.0 },
  },
  Oscilloscope: {
    type: 'Oscilloscope',
    label: 'Oscilloscope',
    category: 'visualization',
    color: '#00ff88',
    inputs: 1,
    outputs: 0,
    defaultParams: { fftSize: 2048 },
  },
  SpectrumAnalyzer: {
    type: 'SpectrumAnalyzer',
    label: 'Spectrum',
    category: 'visualization',
    color: '#00ddff',
    inputs: 1,
    outputs: 0,
    defaultParams: { fftSize: 2048, minDecibels: -90, maxDecibels: -10 },
  },
  LevelMeter: {
    type: 'LevelMeter',
    label: 'Level Meter',
    category: 'visualization',
    color: '#ffaa00',
    inputs: 1,
    outputs: 0,
    defaultParams: { fftSize: 2048 },
  },
};
